service: stripe-preorder-service
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  memorySize: 128
plugins:
  - serverless-offline
functions:
  funding-status:
    handler: src/endpoints/funding-status.funding_status
    events: 
      - http: 
          path: api/v1/funding-status
          method: GET
          cors:
            origins:
              - http://localhost
          response:
            headers:
              - Access-Control-Allow-Origin: '*'
  has-account:
    handler: src/endpoints/has-account.has_account
    events: 
      - http: 
          path: api/v1/has-account
          method: POST
          cors:
            origins:
              - http://localhost
          response:
            headers:
              - Access-Control-Allow-Origin: '*'
  mailing-list:
    handler: src/endpoints/mailing-list.mailing_list
    events: 
      - http: 
          path: api/v1/mailing-list
          method: POST
          cors:
            origins:
              - http://localhost
          response:
            headers:
              - Access-Control-Allow-Origin: '*'
  create-customer:
    handler: src/endpoints/create-customer.create_customer
    events: 
      - http: 
          path: api/v1/create-customer
          method: POST
          cors:
            origins:
              - http://localhost
          response:
            headers:
              - Access-Control-Allow-Origin: '*'
  attach-token:
    handler: src/endpoints/attach-token.attach_token
    events: 
      - http: 
          path: api/v1/attach-token
          method: POST
          cors:
            origins:
              - http://localhost
          response:
            headers:
              - Access-Control-Allow-Origin: '*'
  create-order:
    handler: src/endpoints/create-order.create_order
    events: 
      - http: 
          path: api/v1/create-order
          method: POST
          cors:
            origins:
              - http://localhost
          response:
            headers:
              - Access-Control-Allow-Origin: '*'
  pay-order:
    handler: src/endpoints/pay-order.pay_order
    events: 
      - http: 
          path: api/v1/pay-order
          method: POST
          cors:
            origins:
              - http://localhost
          response:
            headers:
              - Access-Control-Allow-Origin: '*'
  list-orders:
    handler: src/endpoints/list-orders.list_orders
    events: 
      - http: 
          path: api/v1/list-orders
          method: POST
          cors:
            origins:
              - http://localhost
          response:
            headers:
              - Access-Control-Allow-Origin: '*'