service: stripe-preorder-service
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: apiApp/apiApp.handler
    events: 
      - http: 
          path: /api-v1-place-order
          method: GET
          cors: true
      - http: 
          path: /api-v1-place-order
          method: PUT
          cors: true