service: stripe-preorder-service
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  memorySize: 128
plugins:
  - serverless-offline
functions:
  place-order:
    handler: src/endpoints/place-order.place_order
    events: 
      - http: 
          path: api/v1/place-order
          method: GET
          cors: true
      - http: 
          path: api/v1/place-order
          method: PUT
          cors: true
  funding-status:
    handler: src/endpoints/funding-status.funding_status
    events: 
      - http: 
          path: api/v1/funding-status
          method: GET
          cors:
            origins:
              - http://localhost
          response:
            headers:
              - Access-Control-Allow-Origin: '*'
  has-account:
    handler: src/endpoints/has-account.has_account
    events: 
      - http: 
          path: api/v1/has-account
          method: POST
          cors:
            origins:
              - http://localhost
          response:
            headers:
              - Access-Control-Allow-Origin: '*'
  mailing-list:
    handler: src/endpoints/mailing-list.mailing_list
    events: 
      - http: 
          path: api/v1/mailing-list
          method: POST
          cors:
            origins:
              - http://localhost
          response:
            headers:
              - Access-Control-Allow-Origin: '*'
  create-customer:
    handler: src/endpoints/create-customer.create_customer
    events: 
      - http: 
          path: api/v1/create-customer
          method: POST
          cors:
            origins:
              - http://localhost
          response:
            headers:
              - Access-Control-Allow-Origin: '*'


